import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <style>
        {`@import url('https://fonts.googleapis.com/css2?family=Dosis:wght@200..800&display=swap');`}
      </style>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
